URL_SERVICE = "https://0b46159c-de67-44de-bf3c-a078072ad3fe.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
CREATE_USER_KIT_PATH = "/api/v1/kits/"
