URL_SERVICE = "https://2999b452-a8ff-415d-a497-2a286c23d62e.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
CREATE_USER_KIT_PATH = "/api/v1/kits/"
